layout:
  qmk_keyboard: splitkb/aurora/corne/rev1
  qmk_layout: LAYOUT_split_3x5_3
layers:
  Base:
  - Q
  - W
  - F
  - J
  - B
  - Y
  - U
  - I
  - O
  - P
  - A
  - R
  - S
  - T
  - G
  - M
  - N
  - E
  - L
  - ;
  - Z
  - X
  - C
  - D
  - V
  - K
  - H
  - ','
  - .
  - /
  - {t: Mouse, h: toggle}
  - {t: BACKSPACE, h: Nav}
  - LEFT SHIFT
  - {t: Symb, h: sticky}
  - {t: SPACE, h: Num}
  - {t: RIGHT CONTROL, h: Func}
  Num:
  - ''
  - '6'
  - '5'
  - '4'
  - .
  - ''
  - ''
  - ''
  - ''
  - ''
  - '0'
  - '3'
  - '2'
  - '1'
  - TAB
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - '9'
  - '8'
  - '7'
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - '0'
  - DEL
  - ''
  - ''
  - {type: held}
  - ''
  Nav:
  - ''
  - ''
  - ''
  - ''
  - ''
  - Alt+LEFT
  - ''
  - ''
  - Alt+RIGHT
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - LEFT
  - DOWN
  - UP
  - RIGHT
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - Gui+LEFT
  - PG DN
  - PG UP
  - Gui+RIGHT
  - ''
  - ''
  - {type: held}
  - ''
  - ''
  - ''
  - ''
  Symb:
  - ''
  - ''
  - '='
  - +
  - ''
  - '"'
  - '-'
  - _
  - '|'
  - \
  - '!'
  - '@'
  - '#'
  - $
  - '%'
  - ^
  - '&'
  - '*'
  - (
  - )
  - ''
  - ''
  - '~'
  - '`'
  - ''
  - ''''
  - '{'
  - '}'
  - '['
  - ']'
  - {t: Base, h: toggle}
  - ''
  - ''
  - {type: held}
  - ''
  - ''
  Mouse:
  - ''
  - ''
  - ''
  - ''
  - ''
  - '&msc SCRL_LEFT'
  - '&msc SCRL_UP'
  - '&msc SCRL_DOWN'
  - '&msc SCRL_RIGHT'
  - ''
  - LCTRL
  - LALT
  - LGUI
  - LSFT
  - ''
  - '&mmv MOVE_LEFT'
  - '&mmv MOVE_DOWN'
  - '&mmv MOVE_UP'
  - '&mmv MOVE_RIGHT'
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - {t: Base, h: toggle}
  - ''
  - ''
  - '&mkp RCLK'
  - '&mkp LCLK'
  - '&mkp MCLK'
  Func:
  - ''
  - F6
  - F5
  - F4
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - F3
  - F2
  - F1
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - F10
  - F8
  - F7
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - F12
  - F11
  - ''
  - ''
  - ''
  - {type: held}
combos:
- p: [2, 3]
  k: LGUI
  l: [Base, Num, Nav, Symb]
- p: [6, 7]
  k: RGUI
  l: [Base, Num, Nav, Symb]
- p: [1, 2]
  k: Meh+LCMD
  l: [Base, Nav, Num, Symb]
- p: [7, 8]
  k: Meh+LCMD
  l: [Base, Num, Nav, Symb]
- p: [11, 13]
  k: TAB
  l: [Base, Num, Nav, Symb]
- p: [12, 13]
  k: A
  l: [Base, Num, Nav, Symb]
- p: [17, 18]
  k: RET
  l: [Num, Base, Nav, Symb]
- p: [11, 12]
  k: BACKSPACE
  l: [Base, Num, Nav, Symb]
- p: [16, 17]
  k: ESC
  l: [Base, Num, Nav, Symb]
- p: [21, 22]
  k: LSFT
  l: [Base, Num, Nav, Symb]
- p: [27, 28]
  k: RALT
  l: [Base, Num, Nav, Symb]
- p: [22, 23]
  k: Sft+Ctl+LALT
  l: [Base, Num, Nav, Symb]
- p: [26, 27]
  k: Sft+Ctl+LALT
  l: [Base, Num, Nav, Symb]
- p: [16, 18]
  k: {t: Base, h: toggle}
  l: [Base, Num, Nav, Symb]
